<a href="https://colab.research.google.com/github/joscelino/Templates-e-Codigos-Basicos-em-Python/blob/master/Autovalores_Autovetores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importacao das bibliotecas
import numpy as np
import numpy.linalg as al

In [0]:
# Definicao das matrizes
A = np.array([[4, 2, 0], [-1, 1, 0], [0, 1, 2]])
B = np.diag([3, 2, 1])

In [3]:
A

array([[ 4,  2,  0],
       [-1,  1,  0],
       [ 0,  1,  2]])

In [4]:
B

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 1]])

In [0]:
autovalores, autovetores = al.eig(B)

In [6]:
autovalores

array([3., 2., 1.])

In [8]:
autovetores # Cada coluna se refere a um autovetor

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
autovalores, autovetores = al.eig(A)

In [10]:
autovalores

array([2., 2., 3.])

In [11]:
autovetores # Cada coluna se refere a um autovetor

array([[ 0.00000000e+00,  4.44089210e-16, -8.16496581e-01],
       [ 0.00000000e+00, -4.44089210e-16,  4.08248290e-01],
       [ 1.00000000e+00,  1.00000000e+00,  4.08248290e-01]])

In [12]:
A.dot(autovetores[:,0])

array([0., 0., 2.])

In [13]:
A.dot(autovetores[:,1])

array([ 8.8817842e-16, -8.8817842e-16,  2.0000000e+00])

In [14]:
A.dot(autovetores[:,2])

array([-2.44948974,  1.22474487,  1.22474487])

In [0]:
# Serie de Fibonnacci

In [38]:
n = 8 # Posicao da Serie de Fibonacci
s = np.sqrt(5)
r = 1/s
u = r*(((1+s)/2)**(n+1)-((1-s)/2)**(n+1)) # Valor Fibonacci
print(u)

34.00000000000001
