<a href="https://colab.research.google.com/github/joscelino/Templates-e-Codigos-Basicos-em-Python/blob/master/Calculo_de_Determinantes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from numpy.linalg import det

In [2]:
A = np.array([[1, 2, 4], [5, 3, -1], [7, 2, 0]])
A

array([[ 1,  2,  4],
       [ 5,  3, -1],
       [ 7,  2,  0]])

In [3]:
det_A = np.linalg.det(A)
det_A

-56.00000000000002

In [4]:
B = np.array([[2.3, 7, 15], [0, -3, -1], [7, -2, 10]])
B

array([[ 2.3,  7. , 15. ],
       [ 0. , -3. , -1. ],
       [ 7. , -2. , 10. ]])

In [5]:
det_B = det(B)
det_B

192.39999999999998

In [6]:
# Matriz AZ Nula
AZ = np.zeros([3, 3])
AZ

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
# PROPRIEDADES

In [7]:
# 1) Determinante de matriz nula = 0
det(AZ)


0.0

In [9]:
# 2) det(A) = det(A.T)
det(A.T)

-55.99999999999997

In [10]:
# 3) Se B= k*A[0,:], det(B) = k* det(A)
k = 3
B = A.copy()
B[0, :] = k*B[0, :]
B

array([[ 3,  6, 12],
       [ 5,  3, -1],
       [ 7,  2,  0]])

In [11]:
det(B)

-167.99999999999997

In [12]:
k*det(A)

-168.00000000000006

In [0]:
# 4) Se trocarmos a posicao de duas linhas o det muda de sinal
L1 = A[0, :] # linha 1
L2 = A[1, :] # linha 2
L3 = A[2, :] # linha 3

In [15]:
C = np.array([L2, L1, L3])
C

array([[ 5,  3, -1],
       [ 1,  2,  4],
       [ 7,  2,  0]])

In [16]:
det(C)

56.00000000000002

In [17]:
det(A)

-56.00000000000002

In [0]:
# 5) Matriz com duas linhas iguais -> det = 0

In [19]:
D = np.array([L1, L1, L2])
D

array([[ 1,  2,  4],
       [ 1,  2,  4],
       [ 5,  3, -1]])

In [20]:
det(D)

0.0

In [0]:
# Det(A+B) != det(A) + det(B)

In [22]:
A = np.array(([1, 2, 4], [3, 3, -1], [7, 2, 0]))
B = np.array(([0, 5, 4], [8, 2, 1], [9, -2, 3]))
np.array_equal(det(A+B), det(A)+det(B))

False

In [0]:
# 7) det(A.dot(B)) = det(A)*det(B)

In [23]:
det(A.dot(B))

15192.000000000002

In [24]:
det(A) * det(B)

15191.999999999989